---
title: "01_zhang"
author: "Darren Norris"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    toc: yes
    toc_float: yes
    toc_depth: 3
    fig_caption: yes
  bookdown::pdf_document2:
    toc: yes
    toc_depth: 3
    number_sections: yes
    extra_dependencies: flafter
    highlight: tango
    includes:
      in_header: preamble.txe
always_allow_html: yes
urlcolor: blue
toc-title: Contents
header-includes:
  - \counterwithin{figure}{section}
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(
  echo = TRUE, collapse = TRUE,
  comment = "#>" 
  )
def_hook <- knit_hooks$get("output")
knit_hooks$set(output = function(x, options) {
  out <- def_hook(x, options)
  return(paste("\\begin{framed}\\begin{verbatim}", x, "\\end{verbatim}\\end{framed}", collapse = "\n"))
})
```

\newpage{}

Zhang 2023 https://doi.org/10.1016/j.oneear.2023.01.003
Data from https://doi.org/10.6084/m9.figshare.21723476
```{r}
load("~/Articles/2024_Norris_trytofail/Zhang_2023_code_data/Rawdata.Rdata")
ce_dois <- read_rds("data/ce_dois.RDS")
ce_dois %>% left_join(merge.dat, by=c("doi_clean"= "DI")) %>% 
  filter(!is.na(AU)) -> zhang_abs
write_rds(zhang_abs, "data/zhang_abss.RDS")
  
```

