---
  title: "02_scopus_wos"
author: "Darren Norris"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
  toc: yes
toc_float: yes
toc_depth: 3
fig_caption: yes
bookdown::pdf_document2:
  toc: yes
toc_depth: 3
number_sections: yes
extra_dependencies: flafter
highlight: tango
includes:
  in_header: preamble.txe
always_allow_html: yes
urlcolor: blue
toc-title: Contents
header-includes:
  - \counterwithin{figure}{section}
---
  
```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(
  echo = TRUE, collapse = TRUE,
  comment = "#>" 
)
def_hook <- knit_hooks$get("output")
knit_hooks$set(output = function(x, options) {
  out <- def_hook(x, options)
  return(paste("\\begin{framed}\\begin{verbatim}", x, "\\end{verbatim}\\end{framed}", collapse = "\n"))
})
```

\newpage{}

## Seaarch strategy
1. Make sure WOS and Scopus results are same for same journal.
2. Results for same journal include all those from Conservation Evidence and Williams 2020 
The past and future role of conservation science in saving
biodiversity https://doi.org/10.1111/conl.12720

## Packages
```{r load-packages, warning=FALSE, message=FALSE}
# Data processing and presentation
library(plyr) # plyr before tidyverse
library(tidyverse)
library(stringr)
library(textclean)
library(readxl)
library(gridExtra)
library(magrittr)
# bibliometric
library(rscopus)
library(bibliometrix)
library(metagear)


```

Test scopus search 
```{r get-pii}
options("elsevier_api_key" = "0c6d56570f89faf767669d9ae8cdd873")
have_api_key()
print(rscopus::get_api_key(), reveal = TRUE)

# Abstracts and doi from pii
 x = abstract_retrieval("S1053811915002700", identifier = "pii",
   verbose = FALSE)
 # Abstract text
 x$content$`abstracts-retrieval-response`$coredata$`dc:description`
 # Doi
 x$content$`abstracts-retrieval-response`$coredata$`prism:doi`
 
# scopus_search fails. Bad Request (HTTP 400).
 dsge_query <- rscopus::scopus_search("TITLE-ABS-KEY(DSGE) OR TITLE-ABS-KEY(\"Dynamic Stochastic General Equilibrium\")", view = "COMPLETE")

```

